version: '3'

services:
  node:
    container_name: express
    restart: always
    build: .
    ports:
      - '3000:3000'
    links:
      - mongo
    volumes:
      - .:/usr/src/app
  mongo:
    container_name: mongodb
    image: mongo
    ports:
      - '27018:27017'
    logging:
      driver: none
